version: '3'
services:
  server:
    image: 'ghcr.io/morten-olsen/mini-loader:latest'
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - data:/app/data
    ports:
      - 4500:4500
volumes:
  data:
